apiVersion: v1
kind: Service
metadata:
  name: nginxsvc
  labels:
    app: nginx
spec:
  type: LoadBalancer
  ports:
  - port: 8090
    protocol: TCP
    name: http
    targetPort: 80
  - port: 4443
    protocol: TCP
    name: https
    targetPort: 443
  externalIPs:
  - 192.168.99.101
  selector:
    app: nginx
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: my-nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: ymqytw/nginxhttps:1.5
        command: ["/home/auto-reload-nginx.sh"]
        ports:
        - containerPort: 80
        - containerPort: 443
      # Mount volume into pod
        volumeMounts:
          # must match the name of the volume name below
          - name: shared-html
            # mount path within the container
            mountPath: /usr/share/nginx/html
    # volumes to be mounted to containers
      volumes:
      - name: shared-html
        persistentVolumeClaim:
          claimName: myclaim-1
