apiVersion: v1
kind: Service
metadata:
  name: nginxsvc
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
  - port: 8090
    protocol: TCP
    name: http
    targetPort: 80
  - port: 4443
    protocol: TCP
    name: https
    targetPort: 443
  externalIPs:
  - 192.168.99.101
  selector:
    app: nginx
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: my-nginx
spec:
  replicas: 10
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginxhttps
        image: ymqytw/nginxhttps:1.5
        command: ["/home/auto-reload-nginx.sh"]
        ports:
        - containerPort: 443
        - containerPort: 80
     volumeMounts:
      - mountPath: "/usr/share/nginx/html"
        name: mypd

  volumes:
    - name: mypd
      persistentVolumeClaim:
       claimName: myclaim-1

